# Generated by Django 4.2.7 on 2023-12-19 19:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='body',
            new_name='substance',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='url_img',
        ),
        migrations.AddField(
            model_name='product',
            name='symbol',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
